### ISSUE TITLE
No module named 'mamba_ssm.ops.triton.layernorm'

### ISSUE THREAD

**Issue by 6eternal6** [xi-j/Mamba-TasNet#1]
"from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn"  have error，when use try except to import, such as
 "try:
         from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn
except ImportError:
        RMSNorm, layer_norm_fn, rms_norm_fn = None, None, None"  
the python console does not return an error, but RMSNorm, layer_norm_fn, rms_norm_fn = None, None, None

We looked through dir(mamba_ssm.ops.triton) , but layernorm does exist.

**Comment by xi-j** [comment]
Make sure the version of mamba_ssm is compatible to your hardware and CUDA.
The below packages & versions work for us (see requirements.txt):
causal-conv1d==1.1.3.post1
mamba-ssm==1.1.3.post1
torch==2.0.1 --index-url https://download.pytorch.org/whl/cu118

**Comment by hgdzhx** [comment]
Is this problem solved? “causal_conv1d-1.2.1 + mamba_ssm-2.2.4 ” also has the same problem

**Comment by doris-li-bunny** [comment]
> "from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn" have error，when use try except to import, such as "try: from mamba_ssm.ops.triton.layernorm import RMSNorm, layer_norm_fn, rms_norm_fn except ImportError: RMSNorm, layer_norm_fn, rms_norm_fn = None, None, None" the python console does not return an error, but RMSNorm, layer_norm_fn, rms_norm_fn = None, None, None
> 
> We looked through dir(mamba_ssm.ops.triton) , but layernorm does exist.

hi did you solve this problem? or can i just replace the layernorm with layer_norm?

**Comment by hcp6897** [comment]
from **mamba_ssm.ops.triton.layer_norm** import RMSNorm, layer_norm_fn, rms_norm_fn
